name: &name "Yiannis Papadopoulos"
email: &email giannis.papadopoulos@gmail.com
github_username: &github_username ipapadop
gitlab_username: &gitlab_username ipapadop
twitter_username: &twitter_username ipapadop
stackoverflow_username: &stackoverflow_username "487362"
linkedin_username: &linkedin_username ipapadop
#orcid_id: 0000-0003-4983-5052

title: Yiannis Papadopoulos

author:
  name: *name
  email: *email

description: >-
  Mostly C++, Supercomputing, some ML.

remote_theme: jekyll/minima@d4d779a

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

baseurl: ""
url: "https://ipapadop.github.io"
google_analytics: UA-178385228-1
show_downloads: false
show_drafts: false
permalink: /:categories/:year/:month/:day/:title/

markdown: kramdown

#
# minima options

minima:
  skin: classic

  nav_pages:
    - about.md

  show_excerpts: true

  google_analytics: UA-178385228-1

  date_format: "%b %-d, %Y"

  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/ipapadop"
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/ipapadop/"
    - title: Twitter
      icon: x-twitter
      url: "https://twitter.com/ipapadop"
    - title: StackOverflow
      icon: stack-overflow
      url: "https://stackoverflow.com/users/487362"
    - title: GitLab
      icon: gitlab
      url: "https://gitlab.com/ipapadop"
 
disqus:
  shortname: ipapadop-github-pages

# jekyll-seo-tag
twitter:
  username: *twitter_username

defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      comments: true
